export { default as HomeRoute }  from './HomeRoute/Homeroute'
export { default as Page2Route } from './Page2Route/Page2Route'
export { default as Page3Route } from './Page3Route/Page3Route'
export { default as Page4Route } from './Page4Route/Page4Route'
export { default as UserRoute } from './UserRoute/UserRoute'