/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:eebe8484-9c43-4b1a-9997-4b9c822978a6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qNydNdlvN",
    "aws_user_pools_web_client_id": "66ofpgel8ohjt2o1bfg5m7iuu5",
    "oauth": {}
};


export default awsmobile;
