# serverless.yml

service: my-javascript-backend

custom:
  tableName: 'users-table-${self:provider.stage}'

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: default
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:Get
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
#         - ses:SendEmail
      Resource:

        - { "Fn::GetAtt": ["DynamoDBTable", "Arn" ] }
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName} 

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
        authorizer: aws_iam
        cors: true
      - http: 'ANY /{proxy+}'
        authorizer: aws_iam
        cors: true

resources:
  Resources:
    DynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: commentId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        # ProvisionedThroughput:
        #   ReadCapacityUnits: 1
        #   WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: User-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            # ProvisionedThroughput:
            #   ReadCapacityUnits: 1
            #   WriteCapacityUnits: 1
            Projection:
              ProjectionType: ALL
          - IndexName: Email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            # ProvisionedThroughput:
            #   ReadCapacityUnits: 1
            #   WriteCapacityUnits: 1
            Projection:
              ProjectionType: ALL
          - IndexName: Comment-index
            KeySchema:
              - AttributeName: commentId
                KeyType: HASH
            # ProvisionedThroughput:
            #   ReadCapacityUnits: 1
            #   WriteCapacityUnits: 1
            Projection:
              ProjectionType: ALL


        TableName: ${self:custom.tableName}