
service: sauna-booking-backend

custom:
  tableName: 'sauna-booking'
  cognito_user_pool_arn: 'arn:aws:cognito-idp:eu-west-1:897378097038:userpool/eu-west-1_ez7TepndW'

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: jakoivus
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:Get
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
#         - ses:SendEmail
      Resource:
        # - { "Fn::GetAtt": ["CommentsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminGetUser
      Resource: 
        - 'arn:aws:cognito-idp:eu-west-1:897378097038:userpool/eu-west-1_ez7TepndW'
      # - { "Fn::GetAtt": ["CognitoUserPool", "Arn"] } 
      # - ${self:custom.cognito_user_pool_arn}

  environment:
    DYNAMODB_COMMENTS_TABLE: ${self:custom.tableName}-comments 
    DYNAMODB_USERS_TABLE: ${self:custom.tableName}-users 

    COGNITO_REGION: eu-west-1
    COGNITO_USER_POOL_ID: eu-west-1_ez7TepndW 

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - ${self:custom.cognito_user_pool_arn}

    CommentsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}-comments

    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S

        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}-users
functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY 
          cors: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer 
      - http: 
          path: "{proxy+}"
          method: ANY 
          cors: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer