export  { default as HomePage }  from './HomePage/HomePage'
export { default as UserPage } from './UserPage/UserPage'
export { default as Page2 } from  './Page2/Page2'
export { default as Page3 } from './Page3/Page3'
export { default as Page4 } from './Page4/Page4'