//user
export const GET_USER_DATA = "GET_USER_DATA"
export const SET_USER_DATA = "SET_USER_DATA"
export const REMOVE_COMMENTS = "REMOVE_COMMENTS"
export const ADD_COMMENTS = "ADD_COMMENTS"
export const GET_COMMENTS = "GET_COMMENTS"
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER = 'UPDATE_USER';